[package]
name = "funnyx-socket-msg"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "FunnyX socket message layouts and encode/decode"
readme = false

[dependencies]
funnyx-error = { workspace = true }
funnyx-types = { workspace = true }
bytes = { workspace = true }
serde = { workspace = true }
